src/components/faktum/FaktumNumber.tsx, src/components/faktum/validations.test.tsx, src/components/faktum/validations.ts
Validerer 
- Negativ tall
- Tall med spesiell tegn
- Mellom 0 til 99 for arbeidstimer
- Mellom 0 til 100 for permiteringsprosent
=> DAG-447: Legg til bedre validering på faktum number

src/views/StartSoknad.tsx
=> DAG-451: Ikke disable start soknad knapp på forside

src/components/barn/Barn.tsx, src/components/barn/BarnRegister.tsx, src/components/generator-faktum-card/GeneratorFaktumCard.tsx, src/components/generator-faktum-card/GeneratorFaktumCardWithFakta.tsx, src/pages/api/documentation/[uuid]/index.ts, src/views/StartSoknad.tsx
Fikset problemet hvor man kunne endre svar for barn i oppsummering.
=> Legg til readonly for barnefaktum kort for oppsummering

src/components/inngang-paabegynt/InngangPaabegynt.tsx, src/components/inngang-paabegynt/inngangPaabegynt.module.css, src/components/inngang-send-document/InngangSendDocument.tsx, src/components/inngang-send-document/inngangSendDocument.module.css, src/pages/api/arbeidssoker/index.ts, src/pages/api/soknad/get-mine-soknader.ts, src/pages/arbeidssoker.tsx, src/pages/inngang.tsx, src/views/Inngang.tsx, src/views/arbeidssoker/Arbeidssoker.module.css, src/views/arbeidssoker/Arbeidssoker.tsx
**Arbeidssøkerstatus === "REGISTERED"** 
- Hvis trykker på `Start en ny søknad`: Slett påbegynt søknad og send bruker til start søknad
- Hvis trykker på `Fortsett påbegynt søknad`: Send brukeren til søknaden
**Arbeidssøkerstatus === "UNREGISTERED || UNKNOW"** 
- Hvis trykker på `Start en ny søknad`: Send brukeren til `/arbeidssoker`
- Hvis trykker på `Fortsett påbegynt søknad`: Send brukeren til søknaden
På `/arbeidssoker`
- Hvis trykker på `Registrer seg som arbeidssøker`: send bruker til `https://arbeidssokerregistrering.nav.no/`
- Hvis trykker på `Avbryt`: send bruker til `https://www.nav.no/no/ditt-nav`
- Hvis trykker på `Jeg vil søke om dagpenger likevel`: send bruker til start søknad
`/inngang`
`/arbeidssoker`
=> DAG-535: Lagt til sjekk for arbeidssøkers status på Inngang siden

src/components/exit-soknad/ContinueLaterModal.tsx, src/components/exit-soknad/DeleteSoknadModal.tsx, src/components/exit-soknad/ExitSoknad.module.css, src/components/exit-soknad/ExitSoknad.tsx, src/index.css, src/views/Summary.tsx, src/views/documentation/Documentation.tsx, src/views/soknad/Soknad.tsx
- Lagt til fortsett senere og slett søknad modal nederst i soknadsflyten
- Endret feil med tekstnøkkel
=> Dag-452 slett/fortsett sener modal

src/pages/index.tsx, src/views/start-soknad/StartSoknad.module.css, src/views/start-soknad/StartSoknad.tsx
=> DAG-515: Banner for at du er på ny søknadsdialig

src/views/soknad/Soknad.tsx
Når man kommer til en søknad som ikke er ferdig skal man blir redirekte til riktig seksjon.
=> DAG-550: Redirect bruker til riktig seksjon i søknaden

src/pages/[uuid]/dokumentasjon.tsx, src/pages/[uuid]/index.tsx, src/pages/[uuid]/kvittering.tsx, src/pages/[uuid]/oppsummering.tsx, src/pages/_app.tsx, src/pages/arbeidssoker.tsx, src/pages/index.tsx, src/pages/inngang.tsx
Reduserer ganske mye duplisering av kode på hver eneste page
=> Flytt SanityProvider opp til _app.tsx

next.config.js, package-lock.json, package.json, src/components/timeline/Timeline.tsx, src/hooks/useSvgIcon.ts
Har laget hook for dynamisk import av SVG sånn at vi kan ha alle ikoner tilgjengelig i Sanity uten av bundle size blir kembo
=> Lag hook for dynamic improt av svg fra ds-icons.

src/components/personalia/Personalia.module.css, src/components/personalia/Personalia.tsx, src/components/personalia/personalia.utils.ts
Har lagt på en warning-boks hvis bruker er over 67 år. Den er nesten direkte kopiert fra den gamle på veilederen, bortsett fra at vi nå bruker warning i stedet for info.
Har også fjernet obfuskering av personnummeret, slik at det vises som helhet etter tilbakemelding fra Ingrid.
=> Varsel hvis brukeren er over 67 år gammel

src/components/receipt-arbeidssoker-status/ReceiptArbeidssokerStatus.tsx, src/components/receipt-soknad-status/ReceiptSoknadStatus.tsx, src/pages/[uuid]/kvittering.tsx, src/text-constants.ts
- Sett farge på tag basert på status
- Legg til dato for innsendt tidspunkt på kvittering
- Fjern ukjent status tekstnøkler
- Redirect fra kvittering til søknad hvis søknad har status påbegynt
=> Løser DAG-574, DAG-573, DAG-503

src/components/faktum/FaktumNumber.tsx, src/components/faktum/validation/validations.utils.ts
=> DAG-564: Faktum number uten scrolling med numberic mode

src/api.utils.ts, src/pages/api/documentation/[uuid]/[dokumentkravId]/bundle.ts, src/pages/api/documentation/bundle.ts
=> Lager request id rundt kall til dp-soknad API - tester med bundle først.

src/components/date-picker/DatePicker.tsx, src/components/faktum/FaktumDato.tsx, src/components/faktum/FaktumPeriode.tsx
Til dato på periode faktum er optional, feltet skal ikke gi feilmelding dersom dato er ikke satt
=> DAG-615: Lagt til required props på date picker

src/hooks/dokumentkrav/useEttersending.ts, src/pages/api/documentation/[uuid]/[dokumentkravId]/file/delete.ts, src/text-constants.ts, src/views/ettersending/Ettersending.tsx, src/views/ettersending/EttersendingDokumentkravNotSending.tsx, src/views/ettersending/EttersendingDokumentkravSendingItem.tsx
Hvis du ikke har dokumentkrav for ettersending skal de ikke vises
=> Legg til validering hvis det mangler dokumentkrav ved innsending. 

src/components/file-uploader/FileUploader.tsx
Den gamle måten å sette `isLoading` fungerer ikke når man har flere filer. Endrer dette til en map som returnerer promises (som den alltid gjør når vi kjører asynkrone funksjoner), som gjør at vi kan wrappe det hele i en `Promise.all`. Den vil vente på at alle promises skal kjøre. Profit!
Dokumentasjon på denne måten å awaite løkker: https://zellwk.com/blog/async-await-in-loops/#await-with-map
=> Fikser lasteindikator på filopplasting, nå vises den helt til siste fil er ferdig håndtert

src/components/receipt-upload-documents/ReceiptUploadDocuments.test.tsx, src/context/quiz-context.test.tsx, src/pages/soknad/[uuid]/oppsummering.tsx, src/views/summary/Summary.tsx
Legger på seksjonsheading på oppsummeringssiden fra Sanity + noen ekstra tekster.
I visningen er det tittelen "Oppsummering" som er ny:
=> Seksjonsheading på oppsummeringssiden + tester

src/components/dokumentkrav-generell-innsending/DokumentkravGenerellInnsending.tsx
Lagt til loading state på ettersending knapp for å hindre mulighet for å opprette for mange ettersending uuid
=> Lagt til loading state på ettersending knapp

src/views/start-soknad/StartSoknad.tsx
Lagt inn focus på checkbox på startsiden
=> DAG-621 Legg på fokus på checkbox for samtykke

src/components/barn/Barn.tsx, src/components/barn/BarnBodstedsland.tsx, src/components/barn/BarnNavn.tsx, src/components/barn/BarnRegister.tsx
=> DAG-741: Lagt til mer beskrivende tekst når navn mangles på barnes visnings kortet

package-lock.json, package.json, src/components/faktum/faktum-dato/FaktumDato.test.tsx, src/components/faktum/faktum-dato/FaktumDato.tsx, src/components/faktum/faktum-periode/FaktumPeriode.tsx, src/hooks/faktum/useValidateFaktumDato.ts
Feil er at validering ikke trigger dersom man først fjerne dato også skrive inn en ugyldig dato format rett etter det. Dette er fordi at tom dato felt og ugyldig dato format gir `undefined`.
=> Fikse date picker error ved ugyldig dato etter tom dato

src/components/dropdown/Dropdown.tsx, src/components/faktum/faktum-boolean/FaktumBoolean.tsx, src/components/faktum/faktum-dato/FaktumDato.tsx, src/components/faktum/faktum-envalg/FaktumEnvalg.tsx, src/components/faktum/faktum-flervalg/FaktumFlervalg.tsx, src/components/faktum/faktum-land/FaktumLand.tsx, src/components/faktum/faktum-number/FaktumNumber.tsx, src/components/faktum/faktum-periode/FaktumPeriode.tsx, src/components/faktum/faktum-special-cases/FaktumEgetGaardsbrukArbeidsaar.tsx, src/components/faktum/faktum-text/FaktumText.tsx, src/components/section/Section.tsx, src/context/quiz-context.tsx
Lås alle faktum intill vi får response fra quiz for å blokkere requeter mot quiz som fører til feil nedover i stacken. Legg til å vise kun første ubesvarte faktum i Section siden quiz kun fjerner faktum som har avhengigheter
=> Lås faktum til vi får response fra quiz

src/hooks/useDokumentkravBundler.ts, src/views/dokumentasjon/Dokumentasjon.tsx
Midlertidig fiks for dokumentkrav
=> Set inital state for bundle krav

src/views/summary/Summary.tsx
På oppsummeringssiden sjekket vi tidligere kun om alle søknadens spørsmål hadde blitt svart på (`soknadState.ferdig`). Dette er ikke nok, siden vi også har dokumentkrav som kan være ubesvarte. 
Legger til kode som ikke lar brukeren sende inn søknad hvis ikke alle dokumentkravene er på stell. Legger også på egen "tag" som sier at dokumentkrav er uferdig. Se skjermbilde hvordan det kan se ut hvis bruker mangler dokumentkrav og prøver å sende inn en søknad. Bruker får da opp feilmelding.
Alle tags for å illustrere manglende svar vises nå by default på oppsummeringssiden. Det ga mer mening enn at de dukker opp når bruker prøver å sende inn søknaden.
=> Sjekker om dokumentkrav er svart på på oppsummeringssiden

package-lock.json, package.json, src/api.utils.ts, src/components/error-boundary/ErrorBoundary.tsx, src/components/faktum/faktum-boolean/FaktumBoolean.tsx, src/hooks/useSvgIcon.ts, src/pages/_document.tsx, src/pages/api/.eslintrc, src/pages/api/documentation/[uuid]/[dokumentkravId]/file/save.ts, src/pages/api/logger.ts, src/pages/soknad/[uuid]/dokumentasjon.tsx, src/pages/soknad/[uuid]/ettersending.tsx, src/pages/soknad/[uuid]/index.tsx, src/pages/soknad/[uuid]/kvittering.tsx, src/pages/soknad/[uuid]/oppsummering.tsx, src/pages/soknad/index.tsx, src/views/start-soknad/StartSoknad.tsx
Dette er en PR under arbeid, mer beskrivelse kommer senere. Har opprettet den for å ha noe å snakke rundt. Spørsmålet her er hvordan vi ønsker å bruke disse loggene, er logging på feil uthenting i server side en grei måte å starte på? Ønsker vi logging av dette i det hele tatt i Elastic?
=> Legger til nextjs/pino-logging på utvalgte funksjoner og serverside-fetching av data

src/components/faktum/faktum-text/FaktumText.tsx
FØR DENNE MERGES, må den testes. Får ikke testet før UUID er tilgjengelig igjen
Relatert til https://jira.adeo.no/browse/FAGSYSTEM-281133
=> Fjerner ubrukt kode da det uansett er bevart i git

README.md, src/components/faktum/faktum-text/FaktumText.tsx
Oppdatert dokumentasjon, litt mer rett fram hvordan å få opp løsningen og hva man gjør med en spesifikk bug
=> Oppdatert dokumentasjon

src/components/dropdown/Dropdown.tsx, src/components/faktum/Faktum.tsx, src/components/faktum/faktum-dato/FaktumDato.tsx, src/components/faktum/faktum-envalg/FaktumEnvalg.tsx, src/components/faktum/faktum-land/FaktumLand.tsx, src/components/faktum/faktum-periode/FaktumPeriode.tsx, src/components/faktum/faktum-text/FaktumText.tsx, src/components/progress-bar/ProgressBar.module.css, src/components/progress-bar/ProgressBar.tsx, src/components/sanity/timeline/Timeline.module.css, src/components/sanity/timeline/Timeline.tsx, src/views/arbeidssoker/Arbeidssoker.tsx, src/views/soknad/Soknad.tsx, src/views/summary/Summary.tsx
- Setter autoComplete="off" på inputs
- aria-hidden på svg ikoner
- bruker span isteden for Label
- gjorde om tidslinje komponenten med dl dd dt
- Legge til main for /arbeidsoker siden
=> Fiks for Universell utforming

src/context/user-information-context.test.ts
Meg og gutta som er i praksis hos Nav har laget en kode som skal filtrere ut arbeidsforhold over oppgitt antall måneder. Dette har vi klart å fikse.
=> Filtrer arbeidsforhold Branch

src/components/arbeidsforhold/Arbeidsforhold.module.css, src/components/arbeidsforhold/Arbeidsforhold.tsx
=> Legge til description og readmore i aareg arbeidsforhold modal

src/__tests__/pages/api/soknad/faktum/save.test.ts, src/constants.ts, src/pages/api/soknad/faktum/save.ts
Ref: Code scanning alert på SSRF (Server-side request forgery).
https://github.com/navikt/dp-soknadsdialog/security/code-scanning/19
=> Legge til uuid validering mot SSRF vulnerability

Dockerfile
Det ser ut til å kanskje fjerne noen sårbarheter 🤞
=> Bruk alpine node image
